import {
  Building2,
  Clock,
  PiggyBank,
  Magnet,
  Users,
  Bot,
  Receipt,
  Mail,
  Workflow,
  HeartPulse,
  Home,
  Megaphone,
  ShoppingCart,
  Landmark,
  Cloud,
  UserSearch,
  GraduationCap,
  Truck,
  Briefcase,
  MessageCircle,
  RefreshCw,
  CalendarCheck,
  UserPlus,
  PhoneCall,
  PencilRuler,
  Hammer,
  Rocket,
  Zap,
  Settings2,
  LifeBuoy,
  type LucideIcon,
} from 'lucide-react'

export const iconMap: Record<string, LucideIcon> = {
  building2: Building2,
  clock: Clock,
  piggyBank: PiggyBank,
  magnet: Magnet,
  users: Users,
  bot: Bot,
  receipt: Receipt,
  mail: Mail,
  workflow: Workflow,
  heartPulse: HeartPulse,
  home: Home,
  megaphone: Megaphone,
  shoppingCart: ShoppingCart,
  landmark: Landmark,
  cloud: Cloud,
  userSearch: UserSearch,
  graduationCap: GraduationCap,
  truck: Truck,
  briefcase: Briefcase,
  messageCircle: MessageCircle,
  refreshCw: RefreshCw,
  calendarCheck: CalendarCheck,
  userPlus: UserPlus,
  phoneCall: PhoneCall,
  pencilRuler: PencilRuler,
  hammer: Hammer,
  rocket: Rocket,
  zap: Zap,
  settings2: Settings2,
  lifeBuoy: LifeBuoy,
}

export function getIcon(name: string): LucideIcon {
  return iconMap[name] ?? Workflow
}
